name: Context

env:
 MY_VAR: 'workflow'
on:
 push
jobs:
 github-context:
  runs-on: ${{matrix.os}}
  strategy:
   matrix:
    os: 
     - ubuntu-latest
     - windows-latest
    node-version: [v22, v21]
  steps:
   - uses: actions/setup-node@v4
     with:
      node-version: ${{matrix.node-version}}
   - name: Perform test
     run: echo '${{matrix.os}} and ${{matrix.node-version}}'
 display-info:
     needs: github-context
     runs-on: ubuntu-latest
     steps:
      - run:  echo 'Display Info'
