name: Context

env:
 MY_VAR: 'workflow'
on:
 push
jobs:
 github-context:
  runs-on: ubuntu-latest
  env:
   MY_VAR: 'jobs'
  steps:
   - name: Display 
     env:
      MY_VAR: 'steps'
     run: echo '${{env.MY_VAR}}'
  
